# Welcome to Jekyll!
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Siyu He|Homepage
author: Siyu
email: sh3846@columbia.edu
#bio:  Engineer. Designer. Jack of all trades. Great at Product, Clojure, coaching and debugging.
#description: > # this means to ignore newlines until "show_exerpts:"
#  I solve business problems using design and code. I build APIs, craft user experiences, and mentor designers & devs. My toolbox consists of Coaching, Clojure, Javascript, Vue, Angular, CSS, Product Design, UX, and UI.
current: >  
  I'm currently a graduate student at Columbia BME. My primary research project is to engineer tissue and model disease.
previous: >    
  I got my Bachelor at Xi'an Jiaotong University in China, and major in Physics.
outro: >   
  I like science, and enjoy my life at New York City!
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://alexanderoloo.com"
twitter_username: SiyuHe7
#github_username:  alekcz
sitemap: true

# Build settings
#theme: plainwhite
remote_theme: alekcz/plainwhite-jekyll
plugins:
  - jekyll-feed

plainwhite:
  name: Siyu He
  tagline: Phd candidate @ Columbia
  date_format: "%b %-d, %Y"
  sitemap: true
  # analytics_id: 'UA-112030125-1'

  social_links:
    twitter: SiyuHe7
    linkedIn: in/siyu-he-2a8193128
    # dribbble: siyu

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
